### ISSUE TITLE
<bar hero >and slot_footer.txt problem

### ISSUE THREAD

**Issue by betaprinz** [ComboStrap/website#2] opened 2022-09-01 06:41 UTC
I just downloaded master.zip from Github and copied into my fresh dokuwiki(Igor) for testing.

I installed sqlite, combo and strap plugin. My wiki is without any other plugins.

It seems there is a problem with <bar hero=“lg” > and <bar background-color=“gradient-light” color=“secondary”> element.

It looks strange. I made some screenshot 

I tested my installation with php 7.2 / 7.4.30 and Bootstrap 4/5.

Any Ideas? Did i miss something? Do i need to create own css files?

Sorry I have no clue about web development.

## Bar Hero
https://paste.pics/cfaac1a8fba5568cad2565c05a35da3f

## Grid
https://paste.pics/daeb66e4e0bec22b204917470be922c5

## Footer
https://paste.pics/8462ea8f9debad4601fb1764d49fac2c

My local.php looks like yours except userewrite, useslash and google settings

##### My Local.php

$conf['title'] = 'Wiki';
$conf['template'] = 'strap';
$conf['tagline'] = 'Create your footprint that last ForEver.';
$conf['license'] = '';
$conf['youarehere'] = 1;
$conf['maxseclevel'] = '4';
$conf['useheading'] = '1';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['indexdelay'] = 0;
$conf['htmlok'] = 1;
$conf['target']['extern'] = '_blank';
$conf['useslash'] = 1;
$conf['renderer_xhtml'] = 'combo_renderer';
$conf['plugin']['combo']['MinimalNamesCountForAutomaticCanonical'] = '1';
$conf['plugin']['combo']['disableDokuwikiStylesheet'] = 1;
$conf['plugin']['combo']['prismTheme'] = 'prism';
$conf['plugin']['combo']['lowQualityPageProtectionEnable'] = 1;
$conf['plugin']['combo']['lowQualityPageProtectionMode'] = 'hidden';
$conf['plugin']['combo']['mandatoryQualityRules'] = 'internal_backlinks_min,internal_links_min,words_min';
$conf['plugin']['combo']['svgOptimizationEnable'] = 0;
$conf['plugin']['combo']['svgMaxInlineSizeKb'] = '20';
$conf['plugin']['combo']['outlineNumberingEnable'] = 1;
$conf['plugin']['stale']['admin_only'] = 0;
$conf['tpl']['strap']['footerSlotPageName'] = 'slot_footer';
$conf['tpl']['strap']['headerSlotPageName'] = 'slot_header';
$conf['tpl']['strap']['sidekickSlotPageName'] = 'slot_sidekick';
$conf['tpl']['strap']['privateRailbar'] = 1;
$conf['tpl']['strap']['bootstrapVersionStylesheet'] = '4.5.0 - bootstrap';

**Comment by gerardnico** [comment] 2023-03-15 14:45
Oh men. I miss your report. 

The repository for the issue is [combo](https://github.com/ComboStrap/combo) as indicated in the [contact page](https://combostrap.com/how-to-get-help-with-combostrap-xzqtp19g)

The problem is that the markup used in this repository is for the next release. `bar` is not yet released for instance.

**Comment by gerardnico** [comment] 2023-04-25 08:33
The release has [been made](https://combostrap.com/release/release-1-25-layout-all-the-way-l17jxp17).

This is a big release.

The documentation for:
* the [hero attribute](https://combostrap.com/styling/hero-rdzk927d)
* the [grid](https://combostrap.com/howto/how-to-split-the-horizontal-space-in-two-with-the-grid-component-4lmqzq7b)

I will close this request but if you have any questions, don't hesitate.

**Comment by gerardnico** [comment] 2023-04-25 08:33
I'm going to version the documentation from now on :)  Have a nice day.

**Closed as completed by gerardnico** 2023-04-25 08:33 UTC
